#!/bin/sh
set -e
rm -f prototype.sqlite
sqlite3 prototype.sqlite < prototype-schema.sql
./tools/load-people-xml ./data/stortinget-persons-scraped.xml  
./tools/load-vote-xml \
    ./data/votering-2010-11-19.xml \
    ./data/votering-2011-04-11.xml \
    ./data/votering-2011-03-21.xml \
    ./data/votering-2011-04-04-dld.xml \
    ./data/votering-2011-04-11.xml 
sqlite3 prototype.sqlite < prototype-data.sql
