#!/usr/bin/perl

use warnings;
use strict;

use LWP::Simple;

sub nsd_url {
    my ($id) = @_;
    return "http://www.nsd.uib.no/polsys/index.cfm?UttakNr=33&person=$id";
}

print "<persons>\n\n";

for my $id (1 .. 20500) {
    my $url = nsd_url($id);
#    print "$url\n";
    my $j = LWP::Simple::get($url);
    my $name;
    my @periods;
    if ($j) {
#        print "HTML: '$j'\n";
        my $found = 0;
        my $foundperiods = 0;
        for my $line (split(/\n/, $j)) {
            if ($line =~ m/Representantens navn/) {
#                print "$line\n";
                $found = 1;
            }
            if ($found && $line =~ m%<h1>(.+)</h1>%) {
                $name = $1;
            }
            if ($found && $line =~ m/Representantens stortingsperioder/) {
                $foundperiods = 1;
            }
            if ($foundperiods && $line =~ m%^\s+<td>([^<]+)</td>%) {
                my $period = $1;
                $period =~ s/^(\d{2})(\d{2})-(\d{2})$/$1$2-$1$3/;
                $period = '1898-1900' if ('1898-00' eq $period);
                $period = '1997-2001' if ('1997-01' eq $period);
                push(@periods, $period);
            }
            if ($foundperiods && $line =~ m/Representantens medlemskap i presidentskapet/) {
                $foundperiods = 0;
            }
            if ($found && $line =~ m/Representantens diverse/) {
                $found = 0;
            }
        }
    }
    if ($name) {
        print "<person polsys-person-id=\"$id\">\n";
        print "  <name>$name</name>\n";
        map { print "  <period>$_</period>\n" } @periods;
        print "</person>\n\n";
    }
    sleep 10;
}

print "</persons>\n";
