#!/bin/sh
set -e

# Uses tools from the poppler-utils debian package
extract_interests() {
  URLPATH='www.stortinget.no/globalassets/pdf/register-for-stortingsrepresentantenes-og-regjeringsmedlemmenes-verv-og-okonomiske-interesser.pdf'
  mkdir -p "$(dirname $URLPATH)"
  GET https://$URLPATH > $URLPATH
  pdftohtml -xml $URLPATH
  pdftotext $URLPATH
}

attendence() {
  URLPATH=www.stortinget.no/no/Representanter-og-komiteer/Representantene/Representantfordeling/
  GET https://$URLPATH > ${URLPATH}index.html
}

today=$(date +%Y-%m-%d)
attendence && extract_interests &&
  git commit -m "Inn med web page data fra $today." www.stortinget.no
