#!/bin/sh

set -e

fetch() {
    url="$1"
    file="$url"
    case "$url" in
	*/)
	    file="${url}index.html"
	    ;;
	*/?*)
	    file=$(echo "$url" | sed s%/?%/index.html?%)
	    ;;
	*)
	    ;;
    esac
    if GET "http://$url" > "$file".new ; then
	mv "$file".new "$file"
    else
	echo "Unable to fetch $url. aborting"
	false
    fi
}

current_sessions() {
    grep id data.stortinget.no/eksport/sesjoner/index.html | \
	cut -d'<' -f2 | cut -d'>' -f2|sort -u
}

fetch data.stortinget.no/
fetch data.stortinget.no/eksport/dagensrepresentanter/
fetch data.stortinget.no/eksport/sesjoner/

for id in $(current_sessions); do
    fetch "data.stortinget.no/eksport/saker/?sesjonid=$id"
    fetch "data.stortinget.no/eksport/partier/?sesjonid=$id"
    echo got $id 
done

sakids="$(perl -MXML::Simple -MData::Dumper -e 'my $xml = XMLin("data.stortinget.no/eksport/saker/index.html?sesjonid=2010-2011"); print join(" ", sort keys %{$xml->{saker_liste}->{sak}})')"

sakids="$sakids $(perl -MXML::Simple -MData::Dumper -e 'my $xml = XMLin("data.stortinget.no/eksport/saker/index.html?sesjonid=2011-2012"); print join(" ", sort keys %{$xml->{saker_liste}->{sak}})')"

#sakidwithvotes="48650 49355 49975 47553 50319 50705 40970 40971 48718 45513 48577 46647 46623 49366 47162 49978 47793 48141"
# The ones with votes in the beta data set.
for sakid in $sakids; do
    echo "got votering for sakid=$sakid"
    fetch "data.stortinget.no/eksport/voteringer/?sakid=$sakid"
    for vid in $(GET "http://data.stortinget.no/eksport/voteringer/?sakid=$sakid" |grep '<votering_id>' |sed 's%.*id>\(.*\)</.*%\1%') ; do
	fetch "data.stortinget.no/eksport/voteringsresultat/?voteringid=$vid"
	echo "got voteringsresultat for sakid=$sakid voteringsid=$vid"
    done
done

# Remove "empty" XML files.  Keep going if no files are empty
rm $(grep -l '<voteringsresultat_liste />' data.stortinget.no/eksport/voteringsresultat/index.html\?voteringid\=*) || true

today=$(date +%Y-%m-%d)
git add data.stortinget.no
git commit -m "Inn med data fra $today." data.stortinget.no
