#!/bin/sh

date

set -e
#set -x

ionice -c3 -p $$
renice 10 -p $$

fetch_if_success() {
    thisurl="$1"
    thisfile="$2"
    if GET "$thisurl" > "$thisfile".new ; then
	mv "$thisfile".new "$thisfile"
    else
	false
    fi
}

fetch() {
    url="$1"
    file="$url"
    case "$url" in
	*/)
	    file="${url}index.html"
	    ;;
	*/?*)
	    file=$(echo "$url" | sed s%/?%/index.html?%)
	    ;;
	*)
	    ;;
    esac

    # Try three times, some times the first time fail
    if ! fetch_if_success "http://$url" "$file" ; then
	sleep 2
        if ! fetch_if_success "http://$url" "$file" ; then
	sleep 2
            if ! fetch_if_success "http://$url" "$file" ; then
	        echo "Unable to fetch $url. aborting"
        	false
            fi
        fi
    fi
# Disable sorting, result in XML file perl reject further down. :(
#    case "$url" in
#	*/saker/*)
#	    echo "sorting $url"
#            xmlsort -r /saker_oversikt/saker_liste/sak \
#		-k ./id,n,a "$file" > "$file".new && \
#		mv "$file".new "$file"
#            todos "$file"
#	    ;;
#    esac
}

current_sessions() {
    grep id data.stortinget.no/eksport/sesjoner/index.html | \
	cut -d'<' -f2 | cut -d'>' -f2|sort -u
}

fetch data.stortinget.no/
fetch data.stortinget.no/eksport/dagensrepresentanter/
fetch data.stortinget.no/eksport/fylker/
fetch data.stortinget.no/eksport/emner/
fetch data.stortinget.no/eksport/saksganger/
fetch data.stortinget.no/eksport/stortingsperioder/
fetch data.stortinget.no/eksport/sesjoner/
fetch data.stortinget.no/eksport/allekomiteer/

current_periods() {
    grep id data.stortinget.no/eksport/stortingsperioder/index.html | \
	cut -d\> -f2 | cut -d\< -f1 | sort -u
}

for id in $(current_periods); do
    fetch data.stortinget.no/eksport/representanter/?StortingsPeriodeId=$id || true
    echo got $id
done

for id in $(current_sessions); do
    fetch "data.stortinget.no/eksport/saker/?sesjonid=$id" || true
    fetch "data.stortinget.no/eksport/partier/?sesjonid=$id" || true
    fetch "data.stortinget.no/eksport/komiteer/?sesjonid=$id" || true
    fetch "data.stortinget.no/eksport/sporretimesporsmal/?SesjonId=$id" || true
    fetch "data.stortinget.no/eksport/interpellasjoner/?SesjonId=$id" || true
    fetch "data.stortinget.no/eksport/skriftligesporsmal/?SesjonId=$id" || true
    echo got $id 
done

saksid=""
for id in "2010-2011" "2011-2012" ; do
    sakids="$saksid `perl -MXML::Simple -MData::Dumper -e \"my \\\$xml = XMLin('data.stortinget.no/eksport/saker/index.html?sesjonid=$id'); print join(' ', sort keys %{\\\$xml->{saker_liste}->{sak}})\"`"
done

#sakidwithvotes="48650 49355 49975 47553 50319 50705 40970 40971 48718 45513 48577 46647 46623 49366 47162 49978 47793 48141"
# The ones with votes in the beta data set.
for sakid in $sakids; do
    echo "got votering for sakid=$sakid"
    fetch "data.stortinget.no/eksport/voteringer/?sakid=$sakid"
    for vid in $(GET "http://data.stortinget.no/eksport/voteringer/?sakid=$sakid" |grep '<votering_id>' |sed 's%.*id>\(.*\)</.*%\1%') ; do
	fetch "data.stortinget.no/eksport/voteringsforslag/?voteringid=$vid" || true
	echo "got voteringsforslag for sakid=$sakid voteringsid=$vid"
	fetch "data.stortinget.no/eksport/voteringsresultat/?voteringid=$vid" || true
	echo "got voteringsresultat for sakid=$sakid voteringsid=$vid"
	fetch "data.stortinget.no/eksport/voteringsvedtak/?voteringid=$vid" || true
    done
done

# Remove "empty" XML files.  Keep going if no files are empty
rm $(grep -l '<voteringsresultat_liste />' data.stortinget.no/eksport/voteringsresultat/index.html\?voteringid\=*) || true

today=$(date +%Y-%m-%dT%H%M)
git add data.stortinget.no
git commit -m "Inn med data fra $today." data.stortinget.no
